# 2. What is a Digital Image?

### 🎯 Learning Goals

By the end of this notebook, you should be able to:

* Describe an image as a continuous function, `f(x, y)`.
* Define a *pixel* and its relation to the image matrix.
* Explain the difference between a grayscale image (2D matrix) and a color image (3D matrix).
* Use NumPy to inspect the `shape` and `dtype` of an image.
* Access individual pixel values using matrix indexing.

## Motivation: From the World to a Matrix

In the last notebook, we learned *why* we process images. Now, we'll learn *what* we are processing. How does the rich, continuous visual information of the real world get turned into a block of numbers a computer can understand? 

The answer is that we "digitize" the world, turning a continuous scene into a discrete grid of numbers. This grid is the **digital image**.

## Theory: The Continuous Image `f(x, y)`

We can mathematically model a "perfect" image of the real world as a **continuous function, `f(x, y)`**.

* `(x, y)` are the **spatial coordinates** (where you are in the image, e.g., 9.5cm from the left, 3.2cm from the top).
* `f` is the **intensity** (or brightness/color) of the image at that exact point. 

This function `f` is itself a product of two other functions:

$$f(x, y) = i(x, y) \times r(x, y)$$

* `i(x, y)` is the **illumination**: the amount of light shining on the scene.
* `r(x, y)` is the **reflectance**: the amount of light the object *reflects* (e.g., a white shirt has high reflectance, a black shirt has low reflectance).

The problem is that a computer cannot store a continuous function, which has infinite points. We must *discretize* it.

## Theory: The Digital Image `f[x, y]`

To digitize the continuous function `f(x, y)`, we create a discrete function `f[x, y]` which is stored as a 2D matrix (or 3D, for color). 

Each element in this matrix is called a **Pixel** (short for **Pic**ture **El**ement). A pixel is the smallest individual unit of a digital image, holding a single intensity value (or a set of values, for color).

![Image: Showing a continuous 'Real image' on a grid being converted to a pixelated 'Digital Image](./images/source/n02-continous-to-digital.png)

### Grayscale vs. RGB Images

This matrix representation differs for grayscale and color images (from *PDI-Aula01Parte_1-1, Slide 4*):

#### 1. Grayscale (Monochromatic) Images
* **What it is:** An image with only shades of gray (from black to white).
* **Matrix Representation:** A **2D matrix** (e.g., `Height x Width`).
* **Pixel Value:** Each pixel `f[x, y]` holds a *single number* representing its intensity. For an 8-bit image, this value is typically between 0 (black) and 255 (white).

#### 2. RGB (Color) Images
* **What it is:** A full-color image, created by mixing different amounts of Red, Green, and Blue light.
* **Matrix Representation:** A **3D matrix** (e.g., `Height x Width x 3`). You can think of this as three 2D matrices stacked on top of each other: one for Red, one for Green, and one for Blue. These are called **channels**.
* **Pixel Value:** Each pixel `f[x, y]` holds *three numbers* (a vector) `[R, G, B]`. For a 24-bit image (8 bits per channel), each of R, G, and B is a value between 0 and 255.

*(A 4-channel, or 32-bit, image also exists: **RGBA**. The 4th channel, 'A' for Alpha, represents transparency/opacity.)*

![Greyscale vs RGB vs RGBA](./images/source/n02-greyscale-rgb-rgba.png)

## Python Code: The NumPy Array

In Python, the tool we use for these matrices is the **NumPy array**. Let's create two small, simple images to see this in action.

In [2]:
import numpy as np

### Example 1: A 4x4 Grayscale Image

This is a 2D array. The `shape` will be `(4, 4)`. We use `dtype=np.uint8` which means "unsigned 8-bit integer," the standard type for pixel values from 0-255.

In [3]:
# A small 4x4 grayscale image (a 2D array)
grayscale_img = np.array([
    [10,  50,  80,  120], # Row 0
    [20,  60,  90,  130], # Row 1
    [30,  70,  100, 140], # Row 2
    [40,  80,  110, 150]  # Row 3
], dtype=np.uint8)

print("--- Grayscale Image ---")
print("Shape:", grayscale_img.shape) 
print("Data Type:", grayscale_img.dtype)
print("Full Matrix:\n", grayscale_img)

--- Grayscale Image ---
Shape: (4, 4)
Data Type: uint8
Full Matrix:
 [[ 10  50  80 120]
 [ 20  60  90 130]
 [ 30  70 100 140]
 [ 40  80 110 150]]


### Example 2: A 2x2 RGB Image

This is a 3D array. The `shape` will be `(2, 2, 3)`.

In [4]:
# A small 2x2 RGB image (a 3D array)
# Each pixel has [R, G, B]
rgb_img = np.array([
    # Row 0
    [ [255, 0, 0], [0, 255, 0] ], # [Pixel (0,0) is Red], [Pixel (0,1) is Green]
    # Row 1
    [ [0, 0, 255], [255, 255, 0] ]  # [Pixel (1,0) is Blue], [Pixel (1,1) is Yellow]
], dtype=np.uint8)

print("--- RGB Image ---")
print("Shape:", rgb_img.shape)
print("Data Type:", rgb_img.dtype)
print("Full Matrix:\n", rgb_img)

--- RGB Image ---
Shape: (2, 2, 3)
Data Type: uint8
Full Matrix:
 [[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]


## Accessing Pixel Values

We can access individual pixel values using NumPy's array indexing `[row, column]` or `[row, column, channel]`. 

**Important:** Python/NumPy indexing starts at **0** (it is *0-indexed*). This is different from MATLAB/Octave, which starts at **1** (it is *1-indexed*).

* To get `(row 1, col 2)` in NumPy, you use `[1, 2]`.

In [5]:
# Access pixel at (row 1, col 2) from the grayscale image
# This is the 2nd row, 3rd column
pixel_val = grayscale_img[1, 2]
print(f"Grayscale pixel at [1, 2] is: {pixel_val}") # Should be 90

# Access pixel at (row 1, col 0) from the color image
# This is the 2nd row, 1st column (the Blue pixel)
pixel_vec = rgb_img[1, 0]
print(f"Color pixel at [1, 0] is: {pixel_vec}") # Should be [0, 0, 255]

Grayscale pixel at [1, 2] is: 90
Color pixel at [1, 0] is: [  0   0 255]


## 🧠 Interactive Check / Reflection

Based on the examples above, write the code to answer these two questions:

1.  How would you access the intensity value of the pixel in the **bottom-right corner** of the `grayscale_img`? (It should be `150`).
2.  How would you access just the **Green** value of the pixel in the **top-right corner** of the `rgb_img`? (It should be `255`).

## 📜 Summary

We've learned that a continuous image `f(x, y)` is digitized into a discrete matrix `f[x, y]`. 

* **Grayscale images** are **2D NumPy arrays** (Height, Width).
* **Color (RGB) images** are **3D NumPy arrays** (Height, Width, 3).
* Each element in this array is a **pixel**.
* We access pixels using **0-based indexing**: `image[row, col, channel]`.

## 🚀 Next Steps

We've mentioned 

We've mentioned "digitizing" a continuous image, but we haven't explained *how*. The next notebook, **[03 - Sampling and Quantization](03-sampling-quantization.ipynb)**, will explain the two key processes that make digitization possible.